ablauf: ensure we chain all persist errors to the job
exoscale/ablauf pull request #7
Opened 2020-09-30 14:25 UTC by pyr

2020-09-30 14:29 UTC, pyr commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
The only meaningful change is this one: we bypass coercion to enforcing a future is created for all calls. If `store/persist` already returns a deferred we create an extra deferred but this ensures we can't throw from this function.

2020-10-01 07:27 UTC, mcorbin requested changes

2020-10-01 07:27 UTC, mcorbin commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
It would not be strange to have a deferred inside a deferred (for example: `@(manifold.deferred/future (manifold.deferred/success-deferred {})) => #<SuccessDeferred@1d36cf01: {}>`) ?

2020-10-01 07:27 UTC, mcorbin commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
It would not be strange to have a deferred inside a deferred (for example: @(manifold.deferred/future (manifold.deferred/success-deferred {})) => #<SuccessDeferred@1d36cf01: {}>) ?

2020-10-01 07:50 UTC, wdullaer commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
If I understand this correctly: `persist-result` is only used in the `(d/chain)` a few lines below. `chain` will unwrap all deferreds until it gets to a value, so the outside world will never be aware that it was double wrapped at some point.

2020-10-01 08:32 UTC, wdullaer commented
Fixes #2

2020-10-01 08:55 UTC, mping-exo commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
This is mostly to enforce that `runner` errors are via the returned deferred, am I correct? So you avoid doing a `try/catch`  when calling `runner`

2020-10-01 10:33 UTC, mpenet commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
Couldn't we just enforce the return value of `persist` to be a real deferred? That would make it the responsibility of the caller to spin futures/threads if necessary and keep the whole thing more lean by default.

2020-10-01 11:52 UTC, wdullaer commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
@mping-exo runner would just 'hang' if persist throws. `result` would never be set into a resolved state.
If persist throws, s/consume will finish, but nothing is listening to that deferred.

@mpenet I prefer for a library to be defensive and not make too many assumptions about how consumers implement this. Right now in jobstore, we take some care to ensure that a deferred is returned, but if you pass in data that doesn't pass the spec validation, it will still throw.
At that point your runner just hangs in the current implementation. We may have other places like that, and it will be hard to debug when you finally hit the edge case.
Maybe wrapping a `try/catch` around `store/persist` achieves the same thing, but is less resource consuming?

2020-10-01 12:43 UTC, mping-exo commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
@wdullaer I see, so it's really a required fix. I agree that lib should be defensive (eg: `mem-job-store` is provided by ablauf and doesn't return a deferred), if we don't spin a future at the very least should check/coerce into a deferred. But the future also fixes the "hang" issue, so it's a nice addition.

2020-10-01 12:44 UTC, pyr commented on src/ablauf/job/manifold.clj
> +          persist-result (d/future
> Couldn't we just enforce the return value of persist to be a real deferred?

This was the previous assumption, but ended up causing issues.

> It would not be strange to have a deferred inside a deferred [...]?

Since `d/chain` is used here it resolves all deferreds until it finds a concrete value so it's safe.

> This is mostly to enforce that runner errors are via the returned deferred, am I correct?

Not exactly, errors would hang the consume, but not be surfaced back to the caller.

2020-10-07 06:48 UTC, pyr commented
I think this need to be revisited, allowing for a store failure policy to allow the calling code to control what happens in this case.

2020-10-07 06:48 UTC, closed without merging